# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# ブログのタイトル
title: Japan Azure Identity Support Blog 

# サブタイトル
subtitle: 日本マイクロソフトの Azure Active Directory と AD FS に関するサポート情報のブログです。
description: 日本マイクロソフトの Azure Active Directory と AD FS に関するサポート情報のブログです。
keywords:
  - Azure
  - Azure AD
  - Identity
  - AD FS

author: Azure Identity Support Japan

root_tag_generator:
  root_tag_names:
    - Azure AD
    - AAD Connect
    - AD FS
    - 情報採取
  sub_tag_limit: 20
  sub_tag_sort: 'name' # 未実装
  
# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://jpazureid.github.io/blog/
github:
  url: https://github.com/jpazureid/blog/
  posts_dir: articles
  default_branch: main

skip_render:
  - '_data/*.png'
  - 'BingSiteAuth.xml'
  - 'google4a4cd09c454aa91c.html'

# Deployment
## Docs: https://hexo.io/doc  s/deployment.html
deploy:
  type: git
  repo: git@github.com:jpazureid/blog.git
  branch: gh-pages
  message: "Site updated: {{ now('YYYY-MM-DD HH:mm:ss') }} [skip ci]"

root: /blog/
permalink: :title/
permalink_defaults: 

language: ja
timezone: asia/Tokyo

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
# pagination
archive: 2

new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: true
future: true
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 0
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: jpazure

feed:
  type: atom
  path: atom.xml
  limit: 20

# show disclaimer in all article by default. disableDisclaimer of article's option set true hide.
# ex) 
# ---
# title: Article Title
# date: 2020-04-30 10:00
# disableDisclaimer: true
# ---
disclaimer: ※本情報の内容（添付文書、リンク先などを含む）は、作成日時点でのものであり、予告なく変更される場合があります。

google_analytics: dummy_id