# Header
menu:
  Home: /blog/
  Archives: /blog/archives
rss: /blog/atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
gauges_analytics:
# favicon links are in header.ejs
# favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:

root_tag_generator:
  root_tag_names:
    - Azure AD
    - AAD Connect
    - AD FS
    - 情報採取
  sub_tag_limit: 20
  sub_tag_sort: 'name' # 未実装